# Site settings
# title: Clean Blog
# header-img: img/home-bg.jpg
# email: your-email@yourdomain.com
# description: "Write your site description here. It will be used as your sites meta description as well!"
# baseurl: "/startbootstrap-clean-blog-jekyll"
# url: "http://yourdomain.com"
# twitter_username: SBootstrap
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# # Build settings
# markdown: kramdown
# highlighter: pygments
# permalink: pretty
# paginate: 5
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title:            The Black Tony Stark ( TONY DARK ) And His Thoughts
header-img:       img/home-bg.jpg
description:      "In my spare time I build things. Follow me on my journey to Automate my house and hack everything. #DevOps #sysadmin #python"
logo:             logo.jpg
disqus_shortname: bossjones

#default_bg:       #SOME-IMAGE.JPG
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
#Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://tonydark.io

# Owner/author information
owner:
  name:           Tony Dark
  avatar:         code-bevatar.jpg
  description:    "Making Behance More Awesome"
  email:          bossjones@theblacktonystark.com

  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        bossjones
  github:         bossjones
  facebook_username: iambossjones
  # google_plus: 112974790056521154109

  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    #+joesepi

# Analytics and webmaster tools stuff goes here
#google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    6
paginate_path: "page:num"
excerpt_separator: <!--more-->

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:  /:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      share: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      comments: true
      share: true
